DEFAULT_OFFICES = [
    {
        "name": "Бичура, офис на Кирова",
        "city": "село Бичура",
        "address": "улица Кирова, 12",
        "region": "RU-BU",
        "latitude": 50.5881,
        "longitude": 107.6028,
    },
    {
        "name": "Бичура, сервисный офис",
        "city": "село Бичура",
        "address": "улица Гагарина, 8",
        "region": "RU-BU",
        "latitude": 50.5869,
        "longitude": 107.5999,
    },
    {
        "name": "Тимирязевское, офис продаж",
        "city": "село Тимирязевское",
        "address": "улица Октябрьская, 70",
        "region": "RU-TOM",
        "latitude": 56.4867,
        "longitude": 84.8848,
    },
    {
        "name": "Богашево, склад",
        "city": "Богашево",
        "address": "улица Киевская, 24",
        "region": "RU-TOM",
        "latitude": 56.3666,
        "longitude": 85.1469,
    },
    {
        "name": "Губино, пункт обслуживания",
        "city": "деревня Губино",
        "address": "улица Весенняя, 3",
        "region": "RU-TOM",
        "latitude": 56.509,
        "longitude": 84.701,
    },
]
